services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    restart: unless-stopped
    ports:
      - "3923:3923"
    environment:
      - PUID=1000
      - PGID=1000
      # Enable dotfiles, uploads allowed
      - X_OPTS=--dots
    volumes:
      - /home/agni/apps/docker/copyparty/config:/cfg
      - /home/agni:/w/Agni-Home
      - /mnt/remote/orion-data:/w/Orion-Data
      - /mnt/remote/orion-apps-config:/w/Orion-Configs
      - /mnt/remote/andromeda-apps:/w/Andromeda-Apps
      - /mnt/remote/andromeda-share:/w/Andromeda-Share