global:
  scrape_interval: 15s

scrape_configs:
  # 1. Monitor Agni (Self - Network Core)
  - job_name: 'agni'
    static_configs:
      - targets: ['node-exporter:9100', 'cadvisor:8080']

  # 2. Monitor Prime (Remote - Storage Hub)
  - job_name: 'prime'
    static_configs:
      - targets: ['192.168.0.100:9100', '192.168.0.100:8087']

  # 3. Monitor Legion (Remote - AI & GPU Compute Hub)
  - job_name: 'legion'
    static_configs:
      - targets: ['192.168.0.150:9100', '192.168.0.150:8087', '192.168.0.150:9835']
